name: GitHub Snake

on:
  schedule:
    - cron: '0 * * * *'  # roda a cada hora
  push:
    branches:
      - main  # sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Generate Snake
        uses: platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: snake.svg

      - name: Commit Snake
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add snake.svg
          git commit -m "Update GitHub Snake" || echo "No changes to commit"
          git push
